# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[62,)"
license="MIT"
issueTrackerURL="https://github.com/AngelicTheAngel/weapons_expanded/issues"

[[mods]]
modId="weaponsexpanded"
version="1.9.3"
displayName="Weapons Expanded"
displayURL="https://modrinth.com/mod/weaponsexpanded"
logoFile="weaponsexpanded.png"
authors="AngelicThe_Angel"
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''This mod adds new weapons, enchantments, effects, advancements, and more.'''

[[dependencies.weaponsexpanded]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[62,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.weaponsexpanded]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.2,)"
    ordering="NONE"
    side="BOTH"
