modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="weaponsexpanded"
version="${mod_version}"
displayName="Weapons Expanded"
displayURL="https://modrinth.com/mod/weaponsexpanded"
logoFile= "../../resources/icon.png"
authors="AngelicThe_Angel"
description='''
This mod adds new weapons, enchantments, effects, advancements, and more.
'''

[[mixins]]
config="weaponsexpanded.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"